{{- if and (not .Values.tmdb.existingSecret) .Values.tmdb.apiReadAccessToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "refitdemo.secretName" . }}
  labels:
    {{- include "refitdemo.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiReadAccessToken: {{ .Values.tmdb.apiReadAccessToken | quote }}
{{- end }}
